version: '3.5'

volumes:
  data:

networks:
  templatesbackend-network:
    name: templatesbackend-network

services:
  templatesbackend_backend:
    container_name: templatesbackend-backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/app
      - $HOME/.m2:/root/.m2

    ports:
      - '8080:8080'
    depends_on:
      - templatesbackend-db
    networks:
      - templatesbackend-network

  templatesbackend-db:
    container_name: templatesbackend_pgslq_db
    image: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'dbtemplates'
      POSTGRES_USER: 'dbtemplates'
    ports:
      - '5432:5432'

    networks:
      - templatesbackend-network




