FROM maven:3.8.1-jdk-11
VOLUME /usr/app
WORKDIR /usr/app
ENV TIME_ZONE America/Sao_Paulo
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
ENV JAVA_OPTS ''
EXPOSE 8080
USER 1001
ENTRYPOINT mvn clean package -Dmaven.test.skip && \
  java $JAVA_OPTS -Duser.timezone=$TIME_ZONE -jar target/*.jar templatesbackend.jar
